#page title
page_title                                : Skate Trace                                     # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :   1505771081                                        # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190) 1234793120.

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :   assets/Icon-App-1024x1024.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :   Skate Trace                                 # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Trace competitions and tests of your athletes.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 :                         
your_link                                 : 
your_city                                 :                              
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Track Their Best
    description                           : Designed so that you can track your athletes, both competitively and through their test levels.
    fontawesome_icon_name                 : medal
    
  - title                                 : Different Nations
    description                           : You can specifiy which Country an athlete skates for. If we have a test structure for that Country, it will all be loaded for you automatically.
    fontawesome_icon_name                 : flag

  - title                                 : Security
    description                           : We do not have any access to your data, it is all stored directly on your device. 
    fontawesome_icon_name                 : lock

  - title                                 : Specific to Figure Skating
    description                           : Skate Trace is a bespoke app that targets the world of Figure Skating. 
    fontawesome_icon_name                 : skating

  - title                                 : No Limits
    description                           : As sports coaches, you may have more than a few athletes that you work with. That's why with Skate Trace you can have as many athletes, tests, or competitions as you need. There are no caps.
    fontawesome_icon_name                 : infinity
  
  - title                                 : Assistance
    description                           : First and foremost, Skate Trace has been designed to help you as a coach. It was developed to have a clear place to store information, meaning you don't have to remember it.
    fontawesome_icon_name                 : people-carry

  - title                                 : # Smart App Banner
    description                           : # Display a smart app banner on iOS devices.
    fontawesome_icon_name                 : # arrow-alt-circle-down

  - title                                 : # Social Links
    description                           : # Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : # link

  - title                                 : # FontAwesome Support
    description                           : # Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : # info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               :                   # Replace with alternative image path or image URL.
cover_overlay_color                       : "#007aff"
cover_overlay_transparency                : 1.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#007aff"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#007aff"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#007aff"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
